models:
  gpt-4.1-mini:
    provider: openai
    model_name: gpt-4.1-mini
    max_tokens: 8192
    temperature: 0.0
    max_workers: 10
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 3
    timeout: 60

  gpt-4.1:
    provider: openai
    model_name: gpt-4.1
    max_tokens: 8192
    temperature: 0.0
    max_workers: 10
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 3
    timeout: 60

  o4-mini:
    provider: openai
    model_name: o4-mini
    max_completion_tokens: 8192
    temperature: 1.0
    max_workers: 10
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 3
    timeout: 60

  gpt-5-mini:
    provider: openai
    model_name: gpt-5-mini
    max_completion_tokens: 32768
    temperature: 1.0
    max_workers: 10
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 3
    timeout: 60

  gpt-5:
    provider: openai
    model_name: gpt-5
    max_completion_tokens: 32768
    temperature: 1.0
    max_workers: 10
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 3
    timeout: 60

  internvl3.5:
    provider: openai
    organization: intern
    model_name: internvl3.5-241b-a28b
    max_tokens: 32768
    temperature: 0
    max_workers: 10
    base_url: https://chat.intern-ai.org.cn/api/v1/

  gemini-2.5-pro:
    provider: openai
    organization: google
    model_name: gemini-2.5-pro
    max_tokens: 32768
    temperature: 0
    max_workers: 5
    base_url: https://generativelanguage.googleapis.com/v1beta/openai/

  gemini-2.5-flash:
    provider: openai
    organization: google
    model_name: gemini-2.5-flash
    max_tokens: 32768
    temperature: 0
    max_workers: 5
    base_url: https://generativelanguage.googleapis.com/v1beta/openai/

  gpt-oss-20b:
    provider: together
    model_name: openai/gpt-oss-20b
    max_tokens: 8192
    temperature: 0
    max_workers: 5

  gpt-oss-120b:
    provider: together
    model_name: openai/gpt-oss-120b
    max_tokens: 8192
    temperature: 0
    max_workers: 5

  # claude_4_sonnet:
  #   provider: claude
  #   model_name: claude-4-sonnet-20250514
  #   max_tokens: 1024
  #   temperature: 0.0


  # Gemini_2.5_flask:
  #     provider: gemini
  #     model_name: gemini
  #     max_tokens: 1024
  #     temperature: 0.7