models:
  gpt4.1-nano:
    provider: openai
    model_name: gpt-4.1-nano
    max_tokens: 1024
    temperature: 0.0
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 3
    timeout: 60

  gpt-4.1-mini:
    provider: openai
    model_name: gpt-4.1-mini
    max_tokens: 8192
    temperature: 0.0
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 3
    timeout: 60

  gpt-4.1:
    provider: openai
    model_name: gpt-4.1
    max_tokens: 8192
    temperature: 0.0
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 3
    timeout: 60

  o4-mini:
    provider: openai
    model_name: o4-mini
    max_completion_tokens: 8192
    temperature: 1.0
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 3
    timeout: 60

  gpt-5-mini:
    provider: openai
    model_name: gpt-5-mini
    max_completion_tokens: 32768
    temperature: 1.0
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 3
    timeout: 60

  gpt-4o:
    provider: openai
    model_name: gpt-4o
    max_tokens: 8192
    temperature: 0.0
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_retries: 3
    timeout: 60

  Internvl3.5:
    provider: openai
    organization: intern
    model_name: internvl3.5-241b-a28b
    max_tokens: 32768
    temperature: 0
    base_url: https://chat.intern-ai.org.cn/api/v1/

  # claude_4_sonnet:
  #   provider: claude
  #   model_name: claude-4-sonnet-20250514
  #   max_tokens: 1024
  #   temperature: 0.0


  # Gemini_2.5_flask:
  #     provider: gemini
  #     model_name: gemini
  #     max_tokens: 1024
  #     temperature: 0.7