_common: &common
  env_name: spatial
  train_size: 25
  test_size: 2

# prompt
_prompt_standard: &prompt_standard
  prompt_config:
    topdown: false
    cogmap: false

_prompt_topdown: &prompt_topdown
  prompt_config:
    topdown: true
    cogmap: false

# exp_type
_passive: &passive
  exp_type: passive
  n_objects: 8
  level: 2
  main: 6
  room_size: [15, 15]
  render_mode: vision
  proxy_agent_config:
    type: analyst
    delegate: observer_analyst
    observer_delegate: strategist


_active: &active
  exp_type: active
  n_objects: 8
  max_exp_steps: 15
  room_size: [15, 15]
  level: 2
  main: 6
  render_mode: vision
  calculate_information_gain: false

custom_envs:
  PassiveDir:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *passive
      name: "passive_dir"
      eval_tasks: [{task_type: "dir"}]

  PassiveRot:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *passive
      name: "passive_rot"
      eval_tasks: [{task_type: "rot"}]

  PassiveRotDual:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *passive
      name: "passive_rot_dual"
      eval_tasks: [{task_type: "rot_dual"}]

  PassiveBwdLoc:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *passive
      name: "passive_bwd_loc"
      eval_tasks: [{task_type: "bwd_loc"}]


  PassiveE2A:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *passive
      name: "passive_e2a"
      eval_tasks: [{task_type: "e2a"}]

  PassivePov:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *passive
      name: "passive_pov"
      eval_tasks: [{task_type: "pov"}]

  PassiveFalseBelief:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *passive
      name: "passive_false_belief"
      eval_tasks: [{task_type: "false_belief"}]

  ActiveDir:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *active
      name: "active_dir"
      eval_tasks: [{task_type: "dir"}]

  ActiveRot:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *active
      name: "active_rot"
      eval_tasks: [{task_type: "rot"}]

  ActiveLoc:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *active
      name: "active_loc"
      eval_tasks: [{task_type: "loc"}]
  
  ActiveBwdLoc:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *active
      name: "active_bwd_loc"
      eval_tasks: [{task_type: "bwd_loc"}]


  ActiveE2A:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *active
      name: "active_e2a"
      eval_tasks: [{task_type: "e2a"}]

  ActivePov:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *active
      name: "active_pov"
      eval_tasks: [{task_type: "pov"}]

  ActiveBwdPoV:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *active
      name: "active_bwd_pov"
      eval_tasks: [{task_type: "bwd_pov"}]

  ActiveFalseBelief:
    <<: *common
    env_config:
      <<: *prompt_standard
      <<: *active
      name: "active_false_belief"
      eval_tasks: [{task_type: "false_belief"}]

  
