env1:
    env_name: crossview
    env_config:
        split: train
        type: baseRL
        reward_type: answer-only
    train_size: 20000
    test_size: 0

env2:
    env_name: crossview
    env_config:
        split: test
        type: baseRL
        reward_type: answer-only
    train_size: 0
    test_size: 1053 # 1050
    

