# config.yaml
name: demo_env
render_mode: vision
room_size: [10, 10]
n_objects: 3
level: 0
main: 6

exp_type: active 
perspective: ego
max_exp_steps: 20
calculate_information_gain: true
is_human_eval: true
eval_tasks:
  #- task_type: rot
    #task_kwargs:
      #turn_direction: clockwise
  - task_type: dir
  - task_type: rot
  - task_type: rot_dual
  - task_type: pov
  - task_type: bwd_pov
  - task_type: e2a
  - task_type: fwd_loc
  - task_type: bwd_loc
  - task_type: fwd_fov 
  - task_type: bwd_nav 
  - task_type: false_belief
prompt_config:
  topdown: false
  oblique: false
  type: shorter
  enable_think: true


kwargs:
  model_config:
    model_name: human_player
  override: false
  output_dir: "results"
